### ISSUE TITLE
Add pre-commit instructions to README or Dev Docs

### ISSUE THREAD

**Issue by NirantK** [qdrant/fastembed#106]
> The pre-commit found some left-out formatting changes.

~how to run those?~

I did a manual run, but it would be nice to mention a setup for the hook in dev docs

_Originally posted by @generall in https://github.com/qdrant/fastembed/issues/105#issuecomment-1923358025_

**Comment by Anush008** [comment]
https://github.com/qdrant/fastembed/pull/150
