### ISSUE TITLE
Wrap and support Sparse Vector Creation

### ISSUE THREAD

**Issue by NirantK** [qdrant/fastembed#12]
FastEmbed should/can support sparse vector creation which is based on Bag of Words e.g. TF-IDF and BM25 Okapi. We can launch with existing Python implementations e.g https://pypi.org/project/rank-bm25/

This will help adoption for sparse vectors within the Qdrant ecosystem itself as we can recommend this as the canonical place to make some sparse vectors.

**Comment by generall** [comment]
Alternatively to BM25, we can consider running SLADE-like models. Last time I tried them, the inference speed was my top concern

**Comment by NirantK** [comment]
They continue to be slow, and I don't know of an obvious way to run them with onnxruntime yet. Will keep an eye out on SPLADE though

**Comment by Anush008** [comment]
[#149 ](https://github.com/qdrant/fastembed/pull/146)
New models to follow.
