### ISSUE TITLE
Move deprecation message inside class

### ISSUE THREAD

**Issue by michaelfeil** [qdrant/fastembed#122]
Upon import of fastembed, I am getting `2024-02-16 05:18:24.853 | WARNING  | fastembed.embedding:<module>:7 - DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated. Use TextEmbedding instead. ` 

Can this be moved inside of the respective classes?

**Comment by joein** [comment]
Hi @michaelfeil ,

Thank you for pointing it out!

We will fix it soon

**Comment by Anush008** [comment]
Resolved with https://github.com/qdrant/fastembed/releases/tag/v0.2.2.
