### ISSUE TITLE
Allow to use data parallelization instead of onnx multithreading

### ISSUE THREAD

**Issue by generall** [qdrant/fastembed#14]
Currently, we have a single-threaded loop that feeds batches into multi-threaded onnx runtime.
This is ok we want to minimize latency of the single branch, however in case of the task to encode a lot of documents, data-level parallelism could be more efficient for better throughput.

Suggestion is to allow user to select which type of parallelism is better in which situation:
In case of qdrant integration: use batch-level on queries and data-level on `add`

Data-level parallelism can be implemented using python multiprocessing library. 
It is quite easy to break thins with  multiprocessing, so I suggest to re-use implementation from https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/parallel_processor.py

If data parallelism is used, onnx runtime will be forked across processes and should be configured to only use one thread per fork.

**Comment by do-me** [comment]
That would be a really nice feature. 

I can confirm that for batch operations (like generating 1000 embeddings, CPU-only) normal transformers (already running the model on all available cores afaik) is significantly (~25%) faster. For reference my test code, executed on Python 3.11.0 and an old i7 processor: 

## Transformers 

```python
from transformers import AutoTokenizer, AutoModel
import torch

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-base-en-v1.5')
bge = AutoModel.from_pretrained('BAAI/bge-base-en-v1.5')
bge.eval()

def get_sentence_embeddings(sentences):

    # Tokenize sentences
    encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

    # Compute token embeddings
    with torch.no_grad():
        model_output = bge(**encoded_input)
        # Perform pooling. In this case, cls pooling.
        sentence_embeddings = model_output[0][:, 0]

    # Normalize embeddings, not necessary see https://github.com/UKPLab/sentence-transformers/issues/1084#issuecomment-889124741
    #sentence_embeddings = torch.nn.functional.normalize(sentence_embeddings, p=2, dim=1)

    return sentence_embeddings
```
Executing the function

```python
%%time
# Example usage: 1000 embeddings, CPU-only
sentences = ["urban heat islands"]*1000
embeddings = get_sentence_embeddings(sentences)
```
Result
```
CPU times: total: 11.1 s
Wall time: 5.77 s
```

## Fastembed 

```python
from fastembed.embedding import FlagEmbedding as Embedding
from typing import List
import numpy as np

# ACHTUNG "passage: This is an example passage.",
documents: List[str] = [
    "urban heat islands"
]*1000
embedding_model = Embedding(model_name="BAAI/bge-base-en-v1.5", max_length=512) 
embeddings: List[np.ndarray] = list(embedding_model.embed(documents)) # Note the list() call - this is a generator 
```
Running the model 

```python
%%time
embeddings: List[np.ndarray] = list(embedding_model.embed(documents))
```

Result

```
CPU times: total: 21.7 s
Wall time: 8.87 s
```

**Comment by generall** [comment]
Implemented in https://github.com/qdrant/fastembed/releases/tag/0.1.0
