### ISSUE TITLE
Bug: Data downloading does not work in Binary Quantization from Scratch notebook

### ISSUE THREAD

**Issue by joein** [qdrant/fastembed#174]
### What happened?

It seems like the link format used in data downloading is not valid anymore. 

```bash
git clone https://github.com/qdrant/fastembed.git
python3 -m venv venv && source venv/bin/activate && pip3 install -U pip poetry && poetry install --with dev
jupyter-notebook
```

Then open [Binary Quantization from Scratch.ipynb](https://github.com/qdrant/fastembed/blob/main/docs/experimental/Binary%20Quantization%20from%20Scratch.ipynb) try to run cells sequentially:

<img width="1156" alt="image" src="https://github.com/qdrant/fastembed/assets/22641570/f27197a3-5778-4b74-8896-e1dfa32be5a7">

### Version

0.2.4 (Latest)

**Comment by joein** [comment]
@NirantK could you please look into it?

**Comment by NirantK** [comment]
Ouch, thanks for spotting this — I'll raise a PR this week for this
