### ISSUE TITLE
Slower than HF transformers?

### ISSUE THREAD

**Issue by racinmat** [qdrant/fastembed#203]
The https://qdrant.github.io/fastembed/examples/FastEmbed_vs_HF_Comparison/#results show 
![image](https://github.com/qdrant/fastembed/assets/5525771/dc97d357-8316-4683-a897-0f31ac4d52a8)

do I interpret it correctly that the fastembed is slower than HF transformers?

**Comment by NirantK** [comment]
Looks like an artefact of a specific run where Torch was on GPU while FastEmbed was on CPU. Let me run both on CPU and confirm if this is indeed true.

**Comment by racinmat** [comment]
Thanks. So, is this now both on CPU?

**Comment by NirantK** [comment]
> Thanks. So, is this now both on CPU?

Yes, both on identical M2 Max without Metal optimisations as far as I can tell

**Comment by happy15** [comment]
So the results show that FastEmbed performance better but that much than HF Embed on CPU, right?

A (maybe) related question is: how to make FastEmbed run on M1 Pro with Metal? Following readme it seems just utilize CPU.

Thanks.

**Comment by NirantK** [comment]
> how to make FastEmbed run on M1 Pro with Metal?
It uses the M1 CPU for now

You can fork/clone the repo and add [Silicon](https://pypi.org/project/onnxruntime-silicon/) as a runtime. We don't have a way to test that reliably and hence we don't support it right now.

**Comment by happy15** [comment]
> > how to make FastEmbed run on M1 Pro with Metal?
> > It uses the M1 CPU for now
> 
> You can fork/clone the repo and add [Silicon](https://pypi.org/project/onnxruntime-silicon/) as a runtime. We don't have a way to test that reliably and hence we don't support it right now.

Good to know. Thanks for the reply.
