### ISSUE TITLE
Issue adding fastembed as dependency in poetry due to python requirement

### ISSUE THREAD

**Issue by michaelfeil** [qdrant/fastembed#21]
Installing the current project: infinity_emb (0.0.2)
```
infinity_emb $poetry lock --no-update
Resolving dependencies... (0.1s)

The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - fastembed requires Python >=3.8.0,<3.12, so it will not be satisfied for Python >=3.12,<4.0
```

```
[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "^0.103.2"
fastembed = {version = "^0.0.5", optional=true}
```

**Comment by NirantK** [comment]
ONNX Runtime does not support 3.12 and breaks for that — hence the lock for less than 3.12. We'll support 3.12 when ONNX Runtime does.

**Comment by NirantK** [comment]
Yes, that sounds right. ONNX Runtime does not support 3.12, so Poetry does flag it as broken. I believe that's the desired behaviour for most Poetry use cases.

**Comment by generall** [comment]
onnx issue for the reference https://github.com/microsoft/onnxruntime/issues/18793

**Comment by FcoManueel** [comment]
The ONNX issue that was blocking support for Python version 3.12 has been now resolved: https://github.com/microsoft/onnxruntime/pull/18814

**Comment by FcoManueel** [comment]
With #111 merged this issue seems to be ready to be closed as completed.

Thank you for your work @NirantK !
