### ISSUE TITLE
Need to update package to fix transformers dependency conflict

### ISSUE THREAD

**Issue by NeevrajKB** [qdrant/fastembed#216]

**Comment by NeevrajKB** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.40.1 requires tokenizers<0.20,>=0.19, but you have tokenizers 0.15.2 which is incompatible.
Successfully installed coloredlogs-15.0.1 fastembed-0.2.6 flatbuffers-24.3.25 huggingface-hub-0.20.3 humanfriendly-10.0 loguru-0.7.2 mpmath-1.3.0 onnx-1.16.0 onnxruntime-1.17.3 protobuf-5.26.1 pyreadline3-3.4.1 sympy-1.12 tokenizers-0.15.2 win32-setctime-1.1.0

**Comment by joein** [comment]
available as of `fastembed==0.2.7`
