### ISSUE TITLE
Fastembed hangs when used behind firewall even though local model is present and cache_dir is enforced

### ISSUE THREAD

**Issue by Waffleboy** [qdrant/fastembed#218]
# What
This is an issue which also affects the langchain `FastEmbedEmbeddings` abstraction.

Models can be used offline if the model is already present in `cache_dir`.  However, `FastEmbedEmbeddings` and the underlying `TextEmbeddings` still makes a network query even though the model files are already present. This causes it to hang and eventually timeout, making it unusable behind a firewall.

This behavior seems new, it did not happen with v1.2

# Why does this happen
In short, its cause fastembed calls the huggingface library which makes an API call to check the repo first, before checking if models exist which causes this hang to occur.

Long version:

Im guessing the default is using onyx embedding, and in `fastembed/text/onnx_embedding.py` .

The init statement calls download model:
`self._model_dir = self.download_model(self._model_description, self._cache_dir) `

Onnx embedding inherits this method from `TextEmbeddingBase` which inherits from `ModelManagement` class in `common/model_management.py`,.

`download_model` calls `download_files_from_huggingface` with no other kwargs, which calls `snapshot_download`.

this is defined in `huggingface_hub/_snapshot_download.py`, which has these  Lines 189-191
```python
 # if we have internet connection we retrieve the correct folder name from the huggingface api
    api = HfApi(library_name=library_name, library_version=library_version, user_agent=user_agent, endpoint=endpoint)
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
    assert repo_info.sha is not None, "Repo info returned from server must have a revision sha."
```

# Proof 
Tried it with internet disabled and even though local cache_dir is specified it still makes a network request
<img width="761" alt="image" src="https://github.com/qdrant/fastembed/assets/12254813/0153fc0f-c76c-4903-82d3-3fb2887b54e5">

You can force `local_files_only=True` within  `huggingface_hub/_snapshot_download.py` and this error disappears.

#  How to Replicate
Have the models saved in `BASE_PATH` then run the following code. it will hang.
```python
from langchain_community.embeddings import FastEmbedEmbeddings
user= ''
BASE_PATH = f"/home/{user}/.cache/torch/sentence_transformers/"
embeddings = FastEmbedEmbeddings(model_name="BAAI/bge-base-en-v1.5",cache_dir=BASE_PATH)
```

# Suggested fix

Have fastembed check if the models are present before going further

**Comment by joein** [comment]
However, I think it is still worth adding this parameter, thanks for pointing it out

**Comment by visheshgitrepo** [comment]
> Actually, if you don't have an internet connection, then it works, it raises errors only when you have `SSLError` or `ProxyError`
> 
> And `SSLError` is exactly what you have in your traceback
> 
> ```
> except (requests.exceptions.SSLError, requests.exceptions.ProxyError):
>     # Actually raise for those subclasses of ConnectionError
>     raise
> ```
> 
> If I shut down internet and run
> 
> ```python
> from fastembed import TextEmbedding
> 
> embedding = TextEmbedding(model_name="BAAI/bge-small-en-v1.5", cache_dir='./_model_cache')
> print(list(embedding.embed(["qwe"])))
> ```
> 
> then it works

Its not working for me. Its still trying to connect internet. and giving me HTTPConnectionError. I turned off internet.
And I believe it checks for model.onnx in ./_model_cache

**Comment by joein** [comment]
Hi @visheshgitrepo 

`_model_cache` is my own cache folder I am using in my environment, you need to set your own model or keep the default cache folder. 

You need to run your code with an internet connection first (or put your files into the cache dir), and then you'll be able to use it without internet.

If you need more help, you can describe what you've done and share a code-snippet

**Comment by joein** [comment]
Fastembed requires not only a model file, but also tokenizer path, and some other files, providing just a model file path won't work since it is not sufficient, you need to provide a dir path

**Comment by Waffleboy** [comment]
Fixed by https://github.com/qdrant/fastembed/pull/223

**Comment by lambda-science** [comment]
Hey, I have an error today like this about SSL.
Is there a way to disable SSL check or how can I manually download the model to put it in the right folder ?
`bm25 = SparseTextEmbedding(model_name="Qdrant/bm25")`
![image](https://github.com/qdrant/fastembed/assets/20109584/0ba63d0b-121e-4eb4-b68d-c5a7331cec62)

**Comment by joein** [comment]
discussed here https://discord.com/channels/907569970500743200/1260529217423147058

**Comment by winstxnhdw** [comment]
Could we have better support for offline mode? e.g. have consistent model and tokeniser file formats?
