### ISSUE TITLE
"sentence-transformers/all-MiniLM-L6-v2" - incorrect embeddings and rather slow speedup. 

### ISSUE THREAD

**Issue by michaelfeil** [qdrant/fastembed#22]
I wrote a small unit test. Your models seem to have a couple of issues:
- Inconsistency of created embedding vs Sentence transformers (the sentences are different) - wrong conversion?
- No onnx-gpu

```
sentence_transformers=2.22
fastembed=0.5.0
torch=2.0.0
```

```
import json
import timeit

import numpy as np
from sentence_transformers import SentenceTransformer
from fastembed.embedding import FlagEmbedding

model_name_or_path="sentence-transformers/all-MiniLM-L6-v2"

model_fast = FlagEmbedding(model_name_or_path)
model_st = SentenceTransformer(model_name_or_path)

sample_sentence = [f"{list(range(i))} " for i in range(64)]

got = np.stack(list(model_fast.embed(sample_sentence)))
want = model_st.encode(sample_sentence, normalize_embeddings=True)

# FAILS here Mismatched elements: 24384 / 24576 (99.2%)
np.testing.assert_almost_equal(
    got, want
)

# 2.0177175840362906 vs 2.4251126241870224
print(
timeit.timeit(lambda: list(model_fast.embed(sample_sentence)), number=10), "vs",
timeit.timeit(lambda: model_st.encode(sample_sentence, normalize_embeddings=True), number=10))
```

**Comment by NirantK** [comment]
Thanks for flagging this. Will investigate. 

First guess would be that these are two different models possibly since FlagEmbedding is different from Sentence Transformers.

**Comment by nleroy917** [comment]
Hey!

I've not done a thorough analysis, but I've also had some really quirky results with the `fastembed` embeddings as well. Some similarity scores don't make much sense at all, so I speculate if the embeddings are incorrect.

**Comment by NirantK** [comment]
Hey, I can confirm that the sentence-transforms quantization isn't perfect. The cosine similarity is lower than we'd like. 
The retrieval performance doesn't see too much degradation in a small test that I ran, but yes — this is an important issue.

Thanks for flagging this.

**Comment by nleroy917** [comment]
I am curious if this is still present? I want to use `fastembed` in my docker containers, but not sure if that's feasible with the mismatches

**Comment by I8dNLo** [comment]
So, [this](https://github.com/qdrant/fastembed/issues/22) fix must resolve this issue
