### ISSUE TITLE
Could we update Tokenizers version dependency to ^0.19 from ^0.15?

### ISSUE THREAD

**Issue by rishabgit** [qdrant/fastembed#243]
### What happened?

Not a bug but rather a request - 

Currently, fastembed requires an [old version](https://github.com/qdrant/fastembed/blob/ec8f06978fb9e73f90dc98be1c115225e27978e6/pyproject.toml#L19) (>=0.15,<0.16) which also conflicts with other libraries such as [cohere's python SDK](https://github.com/cohere-ai/cohere-python/blob/ee899df546000356b9d0c2a807a083ccfcd719d4/pyproject.toml#L19)

Latest tokenizers version is `0.19.1`

### What Python version are you on? e.g. python --version

Python 3.10.14, Poetry

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Linux

**Comment by joein** [comment]
Hey @rishabgit , yeah, sure, #244

**Comment by rishabgit** [comment]
Thanks! @joein
