### ISSUE TITLE
Update huggingface-hub dependency?

### ISSUE THREAD

**Issue by pchalasani** [qdrant/fastembed#249]
Is there a good reason there is a caret-constraint `^0.20` on this dependency? This causes a conflict with pkgs that use a more recent version of `huggingface-hub` (which is at 0.23+)

**Comment by joein** [comment]
Hey @pchalasani, thanks for pointing it out, we'll unlock it

Hey @jamescalam, we've already unlocked `tokenizers` in the main brain, it'll be available with the next release

**Comment by pchalasani** [comment]
> Hey @pchalasani, thanks for pointing it out, we'll unlock it

Great, thanks, that was blocking me from using it

**Comment by joein** [comment]
hey @pchalasani, @jamescalam, we've released `fastembed==0.3.0` which should resolve the issue, could you please check if it works for you?
