### ISSUE TITLE
[Bug Request]: Update "tokenizers" dependency

### ISSUE THREAD

**Issue by etsien** [qdrant/fastembed#261]
### What happened?

The tokenizers dependency is too stringent, causing package issues when installing.
Is there a way to bump the dependency?
```
cohere 5.5.0 depends on tokenizers<0.20 and >=0.19
fastembed 0.2.7 depends on tokenizers<0.16 and >=0.15
```

### What Python version are you on? e.g. python --version

Python 3.11
using conda, pip install -r requirements.txt

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Windows

**Comment by joein** [comment]
Hi, we have already fixed it in main branch, we’re going to release it soon

**Comment by joein** [comment]
@etsien we've published release with a fix, could you please try it out with fastembed==0.3.0?
