### ISSUE TITLE
Request for model jinaai/jina-embeddings-v2-base-de

### ISSUE THREAD

**Issue by deichrenner** [qdrant/fastembed#266]
Hi there,

Since the `jinaai/jina-embeddings-v2-base-de` model is one of the most capable models for german text, I'd love to see it supported. 

Is there anything I can help you with?

**Comment by joein** [comment]
Hey @deichrenner 

I think it should be as easy as adding it to https://github.com/qdrant/fastembed/blob/615d6ee2b6dec88b4f85752afbfc25db7eae8ea3/fastembed/text/jina_onnx_embedding.py#L10

Plus, https://github.com/qdrant/fastembed/blob/615d6ee2b6dec88b4f85752afbfc25db7eae8ea3/tests/test_text_onnx_embeddings.py#L8

To compute a canonical vector, we usually take the same model from HF transformers, apply it to some test input, take 5 first values and round to 4 digits.

Would you like to make a contribution?

**Comment by deichrenner** [comment]
Hi @joein, 
Yes, the code changes are reasonably simple. My biggest question was about the quantized model. Who manages those? 
Sure, I'd be more than happy to see all contributions to this topic.
