### ISSUE TITLE
[Model Request]: support for BAAI/bge-reranker-base

### ISSUE THREAD

**Issue by nickprock** [qdrant/fastembed#267]
### What happened?

Hi, I think it would be useful to support at least one ranker, I propose [BAAI/bge-reranker-base](https://huggingface.co/BAAI/bge-reranker-base)

### What Python version are you on? e.g. python --version

Python 3.10

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Linux

**Comment by joein** [comment]
Hi @nickprock 

Yes, we think so as well, we've assigned the reranker task to one of our QSoC participants

**Comment by joein** [comment]
Closing as completed
