### ISSUE TITLE
ImportError: cannot import name 'TextEmbedding' from 'fastembed' (unknown location)

### ISSUE THREAD

**Issue by JamieLee0510** [qdrant/fastembed#269]
The following is the code similar with readme demo code:
```
from fastembed import TextEmbedding

class SelfEmbedding:

    def __init__(self):
        self.embedding_model = TextEmbedding()

    def test_embedding(self):
        documents = [
            "This is built to be faster and lighter than other embedding libraries e.g. Transformers, Sentence-Transformers, etc.",
            "fastembed is supported by and maintained by Qdrant.",
        ]
        embeddings_list = list(self.embedding_model.embed(documents))
        print(embeddings_list[0])
```

but cause the `ImportError: cannot import name 'TextEmbedding' from 'fastembed' (unknown location)` 
seem like the same issue #114 

The code environment is Mac M1 pro with conda py3.11

**Comment by joein** [comment]
Hi @JamieLee0510 

Which fastembed version are you running?

**Comment by JamieLee0510** [comment]
Sorry forgot to mention the version😂
It is `0.1.3` after I run `pip install fastembed`

**Comment by joein** [comment]
I am afraid it's too old, the latest one is 0.3.0

**Comment by JamieLee0510** [comment]
Understood.
Maybe the version issue is from my MacOS or python environment.
