### ISSUE TITLE
[Bug/Model Request]: CI fails too much on downloading models

### ISSUE THREAD

**Issue by generall** [qdrant/fastembed#288]
### What happened?

CI fails on downloading models from hugging-face, most likely hitting some kind of rate limit.

Possible solutions:

- Download less
- Re-try with random backoff
- Add alternative sources

### What Python version are you on? e.g. python --version

All

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

MacOS, Windows

**Comment by joein** [comment]
retry with a backoff (not random though)

https://github.com/qdrant/fastembed/pull/293
