### ISSUE TITLE
[Bug]:  Bug when trying to use FastEmbedEmbeddings()

### ISSUE THREAD

**Issue by jgurule1111** [qdrant/fastembed#296]
### What happened?

I''ve been using FastEmbedEmbeddings for the past few weeks and yesterday it stopped working and I don't know why. Below are pictures of the error messages and my code.

<img width="808" alt="BUG FASTEMBED" src="https://github.com/qdrant/fastembed/assets/131311280/c58a0eda-a02d-4347-bdeb-825470f0b593">
<img width="556" alt="PIC OF BUG" src="https://github.com/qdrant/fastembed/assets/131311280/4e06ead9-9bd3-4f30-a806-62c4459b6ded">

### What Python version are you on? e.g. python --version

Python 3.10

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Windows

**Comment by Apatsi** [comment]
Same error with python 3.9 and latest versions of both langchain-community and fastembed. Any update on this?

**Comment by Anush008** [comment]
Hey guys. The issue is found. There's a PR to fix it and also update the integration.

**Comment by jgurule1111** [comment]
> Can you try updating Langchain Community and FastEmbed to latest?
I tried that, but it didn't work. I figured out the solution: I needed to install my pip dependencies in a specific order. Thank you for your help!
