### ISSUE TITLE
Updated tokenizers to match transformers requirement

### ISSUE THREAD

**Issue by AmanKishore** [qdrant/fastembed#30]
tokenizers version must be >= 0.14

**Comment by NirantK** [comment]
We don't have a transformers dependency, I didn't quite understand the use case. Can you share some context?

**Comment by AmanKishore** [comment]
Here is the conflict:
    transformers 4.34.0 depends on tokenizers<0.15 and >=0.14
    fastembed 0.1.1 depends on tokenizers<0.14 and >=0.13
