### ISSUE TITLE
In AWS Lambda "Unable to import module 'app': /lib64/libm.so.6: version `GLIBC_2.27' not found"

### ISSUE THREAD

**Issue by Karthickrajan-L** [qdrant/fastembed#314]
I created a python package from a ubuntu machine with "ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27" and created a layer in AWS Lambda and attached the same with Lambda function with runtime python 3.10. When I try to trigger a request I'm getting below issue.

"errorMessage": "Unable to import module 'controller.app': /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/python/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so)"

**Comment by pixelcatgg** [comment]
we're also getting this, did you end up solving it @Karthickrajan-L ?

**Comment by pixelcatgg** [comment]
Commenting for what worked for us. 

I asked in the Qdrant discord and was directed to this: https://github.com/aws/aws-lambda-base-images/issues/5

From the AWS Documentation: https://docs.aws.amazon.com/lambda/latest/dg/python-image.html

```
Python 3.12 and later base images are based on the Amazon Linux 2023 minimal container image. The Python 3.8-3.11 base images are based on the Amazon Linux 2 image. AL2023-based images provide several advantages over Amazon Linux 2, including a smaller deployment footprint and updated versions of libraries such as glibc.
```

Using the 3.12 container from AWS has fixed the issue, and fastembed is working in a dockerized python Lambda:
```
FROM public.ecr.aws/lambda/python:3.12
```
