### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by ranjancse26** [qdrant/fastembed#33]
Just noticed a 404 error on https://qdrant.github.io/fastembed/examples/Retrieval%20with%20FastEmbed/

It would be helpful if the docs are up-to date.

**Comment by ranjancse26** [comment]
@NirantK  The repo main page needs to be updated. It still points to old link.

![image](https://github.com/qdrant/fastembed/assets/2565797/8a300c93-6232-4cef-8258-19c367359c15)

**Comment by NirantK** [comment]
Thanks for catching this! Will fix this
