### ISSUE TITLE
[Bug/Model Request]: Import Error

### ISSUE THREAD

**Issue by mustfkeskin** [qdrant/fastembed#342]
### What happened?

pip install fastembed

Cell In[2], line 1
----> 1 from fastembed import ImageEmbedding
      2 import os
      4 root = "../src/images/"

ImportError: cannot import name 'ImageEmbedding' from 'fastembed' (unknown location)

### What Python version are you on? e.g. python --version

Python 3.9

### Version

0.1.x

**Comment by joein** [comment]
hi @mustfkeskin 
could you please tell us the version of fastembed you're using?

**Comment by mustfkeskin** [comment]
fastembed                 0.1.3                    pypi_0

**Comment by joein** [comment]
ImageEmbedding was added in fastembed 0.3.0

**Comment by mustfkeskin** [comment]
When I installed with pip install 0.1.3 was installed
I am trying to upgrade it
