### ISSUE TITLE
Allow any HF feature extraction model to be used in fastembed

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [qdrant/fastembed#36]
There are various models on HuggingFace with the same architecture type as existing supported models (like Bert, XLM Roberta, etc.). It'll be good to allow any of them to be loaded and used in fastembed.

The corresponding model artifacts (if there is some quantization and format conversion happening behind the scenes) should ideally be stored at a permanent location (maybe on HF hub), to allow for easy reproduction.

cc @NirantK

**Comment by NirantK** [comment]
The first part — architecture type: This is out of the scope for the moment. We want to focus on models where we can offer some promise of performance visibility.
