### ISSUE TITLE
Similarity mismatch?

### ISSUE THREAD

**Issue by aliozts** [qdrant/fastembed#37]
In the [documentation](https://qdrant.github.io/fastembed/examples/FastEmbed_vs_HF_Comparison/#are-the-embeddings-the-same) it is said that the embeddings are 99% similar while the respective number is ~0.92. can you please check it?

**Comment by NirantK** [comment]
This is addressed in the documentation now. The mismatch comes from two different versions of the model: the cosine similarity is 0.99 for BAAI/bge-small-en and 0.92 for BAAI/bge-small-en-v1.5
