### ISSUE TITLE
Generalized Thresholding for ColBERT Scores Across Datasets

### ISSUE THREAD

**Issue by FaisalAliShah** [qdrant/fastembed#383]
I’m currently working with ColBERT for document re-ranking and facing challenges in applying a generalized threshold to ColBERT scores across different datasets. Due to the variability in score ranges, it’s difficult to set a fixed threshold for relevance filtering. Unlike typical embedding similarity scores, ColBERT’s late interaction mechanism produces scores that can vary significantly based on query length, token distributions, and dataset characteristics.

I tried using min-max normalization on scores returned for a particular query but turns out even when the search is irrelevant it would give results because I was selecting min_score and max_score from the query responses.

Here are some of the approaches I’ve considered, but each has limitations when applied generally:

Normalizing scores by query length or token count
Rescaling scores based on observed min-max values in different datasets
Z-score normalization based on empirical mean and variance across datasets
Using adaptive thresholds or lightweight classifiers to predict relevance
However, each approach tends to be dataset-specific, and I would like a solution that can generalize effectively across datasets. Do you have any recommended strategies for achieving a more standardized scoring range or threshold? Alternatively, is there any built-in functionality planned (or that I might have missed) for scaling or calibrating ColBERT scores in a more generalizable way?

Any guidance or suggestions would be greatly appreciated! I have attached my code snipped below as how I am using it.

````
prefetch = [
                models.Prefetch(
                    query=dense_embedding,
                    using=dense_vector_name,
                    limit=20,
                ),
                models.Prefetch(
                    query=sparse_embedding,
                    using=sparse_vector_name,
                    limit=20,
                ),
            ]


            
            search_results = self.qdrant_client.query_points(
                collection_name=kwargs["collection_name"],
                prefetch=prefetch if Config.RETRIEVAL_MODE == QdrantSearchEnums.HYBRID.value else None,
                query=dense_embedding if Config.RETRIEVAL_MODE == QdrantSearchEnums.DENSE.value else colbert_embedding,
                using=dense_vector_name if Config.RETRIEVAL_MODE == QdrantSearchEnums.DENSE.value else colbert_vector_name,
                with_payload=True, 
                limit=10,
                # score_threshold=17,
            ).points
            return search_results

**Comment by joein** [comment]
Hi @FaisalAliShah 

In general, we are not practicing thresholds, since it is indeed hard to select a proper threshold.  It can differ significantly not only across various datasets, but even across a single dataset.
This question is also more model-specific, rather than tool specific (qdrant / fastembed), I think that there might be a higher chance to find the answer you're looking for in colbert's repository

**Comment by AshutoshSabic** [comment]
Hi @FaisalAliShah!

I am facing the same challenge. I had also tried 'Normalizing scores by query length or token count' but for a lot of queries I get >1 normalized score for the same dataset. 

Did you experience something similar? I am looking to set the threshold for a single dataset. Would appreciate any help.

Also I am skeptical about other approaches like

Rescaling scores based on observed min-max values in different datasets
Z-score normalization based on empirical mean and variance across datasets
Using adaptive thresholds or lightweight classifiers to predict relevance

**Comment by FaisalAliShah** [comment]
Hi @joein,

Thanks for your kind reply, I have opened the issue colbert repository as well! hopefully I will hear back from them as well. 

Regards, 

Faisal Ali

**Comment by FaisalAliShah** [comment]
Hi @AshutoshSabic,

Yes, you're right. I considered normalizing the score with query_token as well, but as you mentioned, it would still result in scores >1 in most cases. This is primarily because query_token sizes typically range from 10 to 20, and ColBERT generally returns scores >20 for good matches. I also tried min-max normalization, but it had its drawbacks, as I was selecting the min and max from the scores in the responses. This approach would yield a 1 (100% match) score even when there was no actual match in the data. For now, I’ve applied thresholding to the scores returned by ColBERT, but I’m still exploring better solutions for this!

**Comment by AshutoshSabic** [comment]
Hi @FaisalAliShah ,

Thanks a lot for your reply! I received a reply from Omar khattab but don't think it helps. Did you hear from anyone about it? link to the issue- https://github.com/stanford-futuredata/ColBERT/issues/374

![image](https://github.com/user-attachments/assets/82f02156-cb0a-45a9-893a-874f451cab8c)

**Comment by FaisalAliShah** [comment]
Hi @Ashutosh,

No I still haven't heard back from anyone yet! but I have applied relative
max normalization on the scores and it is working fine for me!
here is how it works: when you get the scores of search you find the max
the of those scores and then divide all the the scores with the maximum
score. this way your scores are normalized between 0 and 1. This will also
work for irrelevant results so you have to hard code the colbert threshold(
I have used 17, because on my dataset good results were above this score).


Regards,
Faisal

**Comment by zhuohaoyu** [comment]
Hi @FaisalAliShah @AshutoshSabic, I am also very interested in this, and I suspect that there might be padding or similar logic implemented in qdrant.
From the scoring code in qdrant's codebase: https://github.com/qdrant/qdrant/blob/master/lib/segment/src/vector_storage/query_scorer/mod.rs#L34-L54 
we could see that the score_max_similarity function returns a max_sim score ranging from 0 to len(multi_dense_a). No matter how the function is called (score_max_similarity(query_vectors, doc_vectors), score_max_similarity(doc_vectors, query_vectors)), it should not exceed min(len(query_vectors), len(doc_vectors)). Thus, maybe they implemented a padding logic to set a minimum length for the query vector, I don't know how else it could be explained. I haven't found any related logic in their codebase so I might be wrong.
