### ISSUE TITLE
[Feature]: How can we deploy FastEmbed externally as an Inference service?

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [qdrant/fastembed#395]
### What feature would you like to request?

I would like to deploy fastembed as an external service, similar to [infinity](https://github.com/michaelfeil/infinity). Can we do that?

**Comment by joein** [comment]
Hey @S1LV3RJ1NX 
Fastembed is a library, not an inference server, in order to do that you'd need to write some code, e.g. fastapi backend
