### ISSUE TITLE
[Feature]: Is there a Rust version of the rrf function in the example Hybrid Search with FastEmbed & Qdrant in the documentation?

### ISSUE THREAD

**Issue by qpb8023** [qdrant/fastembed#401]
### What feature would you like to request?

If possible, can document add the rust version of rrf and rank_list function?

**Comment by Anush008** [comment]
You could refer to https://github.com/qdrant/qdrant/blob/master/lib/segment/src/common/reciprocal_rank_fusion.rs#L25 for RRF.
