### ISSUE TITLE
Error occurs when using late interaction model.

### ISSUE THREAD

**Issue by laura-y7860** [qdrant/fastembed#407]
Hello,

I don't know if this is the right palce to raise an issue but, I tried following the demo from qdrant/[workshop-ultimate-hybrid-search](https://github.com/qdrant/workshop-ultimate-hybrid-search) and encountered an error as follows(didn't make any changes to the code provided):
![image](https://github.com/user-attachments/assets/bcc04d92-b843-4fb8-9fcb-99449af36100)

Many Thanks,

**Comment by FaisalAliShah** [comment]
hey there, 

I am also facing kind of similar issue. I am processing texts batch_wise my batch_size is 20, for many batches late-interaction model is working fine but some batches in middle it is giving this error. Any idea how to resolve this issue?

`Error embedding documents: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Expand node. Name:'/bert/Expand' Status Message: /bert/Expand: left operand cannot broadcast on dim 1 LeftShape: {1,512}, RightShape: {20,513}`

**Comment by joein** [comment]
Hey, thanks for rising the issue, we'll look into it

**Comment by laura-y7860** [comment]
Recent commit solved the error. Closing the issue.
