### ISSUE TITLE
Feature Request: Add gte-base (768 dimension) Model to Supported Models

### ISSUE THREAD

**Issue by InshaManowar** [qdrant/fastembed#409]
Hello

I noticed that while the `gte-large` model is currently available, the [`gte-base`](https://huggingface.co/thenlper/gte-base) model (with 768-dimensional embeddings) is not listed among the supported models. I would like to request that you consider adding the gte-base model to your model library.
The model could be valuable for users looking for a more compact embedding solution with good performance characteristics.

Thanks!

**Comment by joein** [comment]
hey @InshaManowar 

it is available as of fastembed 0.5.0
