### ISSUE TITLE
[Feature]: Load a model from a local directory

### ISSUE THREAD

**Issue by devanshkhandekar** [qdrant/fastembed#417]
### What feature would you like to request?

The SparseEmbedding,SparseTextEmbedding class should be able to load the models  from the local path. For example for the below implementation, 

`model_name = "prithivida/Splade_PP_en_v1"`
`qdrant_model = SparseTextEmbedding(model_name=model_name, cache_dir='./onnx-models/')`

Otherwise I dont understand how to use it in the AWS Lambda images.

**Comment by claudiagf98** [comment]
Hi, how did you solve this?
I need to load the model from local path.
Thanks
