### ISSUE TITLE
clarify splitting in documentation

### ISSUE THREAD

**Issue by antonkulaga** [qdrant/fastembed#42]
I am using embeddings to embed scientific papers. Usually, I use langchain splitters to split the paper into multiple chunks. However, it is not clear to me if fastembed will do splitting for me or I have to split everything (for which I will have to run embedding tokenizer to evaluate tokens per each paragraph).

**Comment by NirantK** [comment]
FastEmbed will not do the splitting for you. Our default model expects 512 tokens — these tokens are different from the OpenAI tokens!

**Comment by antonkulaga** [comment]
>these tokens are different from the OpenAI tokens!

Of course, I have a custom splitter (in my case https://github.com/longevity-genie/indexpaper/blob/main/indexpaper/splitting.py#L119 ) that computes the tokens with the selected HuggingFace model and splits accordingly. The problem is that with this approach I have to run the embedding model once again - for splitting and I do not win much time. If fastembed would have a tokenaware splitter built-in it will save a lot of computation.

**Comment by x4080** [comment]
@antonkulaga Yes I thought the same too, is it possible using fastembed to split the texts ?

**Comment by antonkulaga** [comment]
I think the close is premature. You have to measure number of tokens to split the text and for this you need to call embedding one more. As fastembed does not have proper splitting I will have to use way slower langchain implementation that decreases the benefits from fastembed

**Comment by x4080** [comment]
@antonkulaga ok, thanks for the answer

**Comment by NirantK** [comment]
Work in Progress here: #80

**Comment by x4080** [comment]
@NirantK cool
