### ISSUE TITLE
EmbeddingModel is not an abstract class

### ISSUE THREAD

**Issue by joein** [qdrant/fastembed#49]
Inheriting from `abc.ABC` does not prevent creating a class if it has no `@abc.abstractmethod`s
Thus we need either add some abstractmethods to prevent creation of `EmbeddingModel`  or stop inheriting from ABC

Since we create an instance of `EmbeddingModel` in `EmbeddingWorker`, I believe we need to remove inheritance

**Comment by NirantK** [comment]
Good point. Would you recommend adding the `@abc.abstractmethod` here?
