### ISSUE TITLE
Add Sentence Transformer Family Models 

### ISSUE THREAD

**Issue by NirantK** [qdrant/fastembed#5]
Can see the most popular/downloaded ones from HF and support those. Reduce the scope of this issue to fewer models and a specific list

**Comment by danielbichuetti** [comment]
Hi @NirantK. I noticed there are comments inside one of your notebooks about multilingual-e5-large. Will you upload it to GCS?

**Comment by generall** [comment]
`intfloat/multilingual-e5-large` is supported in latest verson
