### ISSUE TITLE
Feature: Option for ONNX on GPU execution provider

### ISSUE THREAD

**Issue by michaelfeil** [qdrant/fastembed#52]
I appreciate the CPU-first design. 

It would be great to switch the execution provider to `GPU/CUDA` - are there any plans on the roadmap to do so?

**Comment by TheSeriousProgrammer** [comment]
Yes this would indeed be helpful when you want to quickly vectorize large passages into chunks. Eg pdf bot

**Comment by equal-l2** [comment]
These lines defines which providers the ONNX runtime uses.
https://github.com/qdrant/fastembed/blob/b01f882df7113b24b37391a8ada65ba5e4886bb7/fastembed/embedding.py#L90-L91

I wonder if simply adding `'CUDAExecutionProvider'` to the list would work.

**Comment by michaelfeil** [comment]
Only Nvidia-GPU works!
