### ISSUE TITLE
Load fine-tuning model using fastembed

### ISSUE THREAD

**Issue by vatsci** [qdrant/fastembed#58]
Hi. Your works are great!
I want to load my fine-tuning model into fastembed.
But i can't find any documentation about that
Can you tell me how to do that?

Thank you

**Comment by NirantK** [comment]
Not at the moment. We want to support models which are quantized, fast and run on ONNX Runtime. This means, we're limited to OSS models at the moment. If your model fits the description, please share the model weights over Google Drive with us and I'll add that to our model library.

**Comment by vatsci** [comment]
I get it. Thank you for your infomation.
