### ISSUE TITLE
Support for thenlper/gte-large

### ISSUE THREAD

**Issue by makretch** [qdrant/fastembed#72]
Hello - Wondering if it's possible to add the `gte` class of models? Thank you!

**Comment by NirantK** [comment]
Model links which we need to assess for quality and speed:

https://huggingface.co/Qdrant/gte-large-onnx-Q
https://huggingface.co/Qdrant/gte-small-onnx
https://huggingface.co/Qdrant/gte-large-onnx
https://huggingface.co/Qdrant/gte-base-onnx

**Comment by NirantK** [comment]
Prefer gte-large-onnx over gte-large-onnx-Q
