### ISSUE TITLE
Support for hugging face paraphrase-multilingual-MiniLM-L12-v2

### ISSUE THREAD

**Issue by mango009** [qdrant/fastembed#89]
Requesting support for paraphrase-multilingual-MiniLM-L12-v2. Thanks.

**Comment by NirantK** [comment]
Work in progress here: 
https://huggingface.co/Qdrant/paraphrase-multilingual-MiniLM-L12-v2-onnx-Q

We'll try to support this in the next 1-2 releases itself

**Comment by Anush008** [comment]
Resolved with #129.
