### ISSUE TITLE
Add support for Image/Multimodal Model

### ISSUE THREAD

**Issue by atarora** [qdrant/fastembed#92]
Considering Qdrant would support "any" kind of embedding, we should have a way to process image/multimodal embeddings.

Is there an existing way to do it through Fastembed?

**Comment by NirantK** [comment]
Can consider adding CLIP support #70

**Comment by NirantK** [comment]
Is there anything other than images or non-CLIP models which we're interested in?

**Comment by NirantK** [comment]
Closing this as duplicate of #70 for now
