### ISSUE TITLE
[Qdrant Client] Use Supported Models API

### ISSUE THREAD

**Issue by NirantK** [qdrant/fastembed#95]
The current Qdrant client uses a hard coded list of FastEmbed supported models. This creates a challenge that everytime we add a new model — we need to update two places: FastEmbed and the Qdrant client. 

The better approach would be for the Qdrant Client to use the Supported models API from FastEmbed itself and use that. With pinned FastEmbed versions, this means that every new release of Qdrant client can support latest models which FastEmbed supports!

https://github.com/qdrant/qdrant-client/blob/efb876fe3915dc5e2855f60a5617e940c84591e5/qdrant_client/qdrant_fastembed.py#L18

**Comment by hiepxanh** [comment]
Yes I wish 1 is API interface an 2 is docker version for this, so I can deploy, restart and make it work on our workflow
